kubernetes:
  serviceLocatorMethod:
    type: "multiTenant"
  clusterLocatorMethods:
    - type: "config"
      clusters:
        - url: http://127.0.0.1:9999
          name: minikube
          authProvider: "serviceAccount"
          skipTLSVerify: false
          serviceAccountToken: ${K8S_MINIKUBE_TOKEN}
        - url: http://127.0.0.2:9999
          name: aws-cluster-1
          authProvider: "aws"
    - type: "gke"
      projectId: "gke-clusters"
      region: "europe-west1"
      skipTLSVerify: true
