app:
  title: Backstage Tugboat Preview
  baseUrl: ${TUGBOAT_DEFAULT_SERVICE_URL}

backend:
  baseUrl: ${TUGBOAT_DEFAULT_SERVICE_URL}
  cors:
    origin: ${TUGBOAT_DEFAULT_SERVICE_URL}
    methods: [GET, POST, PUT, DELETE]
    credentials: true
