name: CI to GHCR 

on:   
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: kerberus-platform

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - run: yarn install

      - run: yarn tsc

      - run: yarn build

      - name: Yarn docker-build-frontend
        run: yarn docker-build-frontend
     
      - name: Yarn docker-build-backend
        run: yarn docker-build-backend

      - name: List docker images
        run: docker images

      - name: Log into registry
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push frontend docker image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/kerberus-dashboard-frontend

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          #[[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag kerberus-dashboard-frontend $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

      - name: Push backend docker image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/kerberus-dashboard-backend

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          #[[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          docker tag kerberus-dashboard-backend $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
