name: CI to GHCR 

on:   
  push:
    branches:
      - main

    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: kerberus-platform

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn install 
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command

      - name: Yarn tsc 
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: tsc # will run `yarn tsc` command

      - name: Yarn build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command

      - name: Yarn build-image-frontend
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build-image-frontend # will run `yarn build-image-frontend` command

      - name: Yarn build-image-backend
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build-image-backend # will run `yarn build-image-backend` command

      - name: Log into registry
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        if: github.event_name != 'pull_request'
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME

          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
